# Generated by Django 4.0.3 on 2022-03-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='capital',
            field=models.BooleanField(default=False),
        ),
    ]
